# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Le Mood' do
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'ProgressHUD'
  pod 'iOSDropDown'
  pod 'SwiftyJSON'
  pod 'SVPinView', '~> 1.0'
  pod 'LZViewPager', '~> 1.2.5'
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'Lightbox'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Le Mood
  
end
