# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Le Mood' do
pod 'Alamofire'
pod 'SDWebImage'
pod 'IQKeyboardManager'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Le Mood

end
